import React, { createContext, useState, useContext, ReactNode } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    findRide: "Find a Ride",
    postTrip: "Post a Trip",
    myRides: "My Rides",
    dashboard: "Dashboard",
    driverConsole: "Driver Console",
    myProfile: "My Profile",
    settings: "Settings",
    settingsDesc: "Configure your account and app preferences.",
    logout: "Logout",
    verifiedStudent: "VERIFIED STUDENT",
    impactCard: "IMPACT CARD",
    co2Saved: "CO2 Saved",
    ridesGiven: "Rides Given",
    nextBadge: "25% more until next badge",
    sharedRidesTitle: "Shared Rides for a Better Campus",
    sharedRidesSubtitle: "Save money, reduce traffic, and meet your fellow students on your way to PUCMM.",
    findRideBtn: "Find Ride",
    suggestedRides: "Suggested Rides",
    viewAll: "View All",
    departure: "Departure",
    arrival: "Arrival",
    seatsLeft: "seats left",
    both: "Both",
    womenOnly: "Only Women",
    menOnly: "Only Men",
    // Consola del Conductor (Driver Console)
    driverStatus: "Driver Status",
    availableForRides: "Available for rides",
    weeklyEarnings: "WEEKLY EARNINGS",
    fuelSaved: "FUEL SAVED",
    scheduledTrips: "Scheduled Trips",
    new: "NEW",
    passengersBooked: "passengers booked",
    waitlisted: "WAITLISTED",
    driverDashboard: "Driver Dashboard",
    manageTrips: "Manage your trips and pending requests.",
    activeNavigation: "ACTIVE NAVIGATION",
    currentPosition: "Current Position",
    passengers: "Passengers",
    capacity: "Capacity",
    seats: "Seats",
    timeLeft: "min left",
    estArrival: "Est. Arrival",
    onBoardPassengers: "On-board Passengers",
    studentId: "Student ID",
    paid: "PAID",
    managePassengers: "Manage Passengers",
    routeAlerts: "Route Alerts",
    routeAlertsDesc: "Heavy traffic detected near Villa Altagracia. Estimated delay: 15 mins.",
    validation: "Validation",
    validationDesc: "Driver license verified. Insurance expires in 45 days.",
    greenPoints: "Green Points",
    greenPointsDesc: "You've earned 450 points this month for sharing your ride!",
    // Perfil (Profile)
    editProfile: "Edit Profile",
    driverScore: "Driver Score",
    tripsCompleted: "TRIPS COMPLETED",
    safeDriverStreak: "SAFE DRIVER STREAK",
    totalEarnings: "TOTAL EARNINGS",
    vehicleDetails: "Vehicle Details",
    plate: "Plate",
    verified: "VERIFIED",
    addNewVehicle: "Add New Vehicle",
    recentActivity: "Recent Activity",
    // Ajustes (Settings)
    accountPreferences: "Account Preferences",
    displayName: "DISPLAY NAME",
    institutionalEmail: "INSTITUTIONAL EMAIL",
    emailCannotChange: "Institutional emails cannot be changed.",
    notifications: "Notifications",
    tripConfirmations: "Trip Confirmations",
    tripConfirmationsDesc: "Receive alerts when a passenger books your trip.",
    chatMessages: "Chat Messages",
    chatMessagesDesc: "Get notified when someone sends you a direct message.",
    appUpdates: "App Updates & News",
    appUpdatesDesc: "Stay informed about new features and campus news.",
    privacySafety: "Privacy & Safety",
    womenOnlyRides: "Women-Only Rides",
    womenOnlyRidesDesc: "Only show my profile to other verified female students.",
    showPhoneNumber: "Show Phone Number",
    showPhoneNumberDesc: "Allow confirmed passengers to see your phone number.",
    discardChanges: "Discard Changes",
    saveChanges: "Save Changes",
    // Mis Viajes (My Rides)
    activeRides: "Active Rides",
    pastRides: "Past Rides",
    passenger: "PASSENGER",
    driver: "DRIVER",
    price: "Price",
    earnings: "Earnings",
    details: "Details",
    message: "Message",
    manage: "Manage",
    // Detalles del Viaje (Ride Details)
    backToResults: "Back to Results",
    institutionalDriver: "INSTITUTIONAL DRIVER",
    smokingFree: "SMOKING FREE",
    travelPreferences: "Travel Preferences",
    noSmallTalk: "No small talk",
    spotifyAvailable: "Spotify available",
    noPets: "No pets",
    musicLover: "Music lover",
    acOnHigh: "AC on high",
    friendlyChat: "Friendly chat",
    singlePassengerSeat: "Single passenger seat",
    rideFare: "Ride fare",
    serviceFee: "Service Fee",
    total: "Total",
    bookThisRide: "Book this Ride",
    cancellationFree: "Cancellation is free up to 2 hours before departure.",
    inHours: "In ~2.5 hours",
    liveRouteInsights: "Live Route Insights (AI)",
    analyzingRoute: "Analyzing route with Google Maps data...",
    viewOnMaps: "View on Maps",
    unableToLoadRoute: "Unable to load live route insights."
  },
  es: {
    findRide: "Buscar Viaje",
    postTrip: "Publicar Viaje",
    myRides: "Mis Viajes",
    dashboard: "Panel Control",
    driverConsole: "Consola Chofer",
    myProfile: "Mi Perfil",
    settings: "Ajustes",
    settingsDesc: "Configura tu cuenta y preferencias de la aplicación.",
    logout: "Cerrar Sesión",
    verifiedStudent: "ESTUDIANTE VERIFICADO",
    impactCard: "TARJETA DE IMPACTO",
    co2Saved: "CO2 Ahorrado",
    ridesGiven: "Viajes Dados",
    nextBadge: "25% más para la siguiente medalla",
    sharedRidesTitle: "Viajes compartidos para un mejor campus",
    sharedRidesSubtitle: "Ahorra dinero, reduce el tráfico y conoce a tus compañeros de camino a la PUCMM.",
    findRideBtn: "Buscar Viaje",
    suggestedRides: "Viajes Sugeridos",
    viewAll: "Ver Todo",
    departure: "Salida",
    arrival: "Llegada",
    seatsLeft: "asientos libres",
    both: "Ambos",
    womenOnly: "Solo Mujeres",
    menOnly: "Solo Hombres",
    // Consola del Conductor (Driver Console)
    driverStatus: "Estado del Chofer",
    availableForRides: "Disponible para viajes",
    weeklyEarnings: "GANANCIAS SEMANALES",
    fuelSaved: "COMBUSTIBLE AHORRADO",
    scheduledTrips: "Viajes Programados",
    new: "NUEVO",
    passengersBooked: "pasajeros reservados",
    waitlisted: "EN LISTA DE ESPERA",
    driverDashboard: "Panel de Chofer",
    manageTrips: "Gestiona tus viajes y solicitudes pendientes.",
    activeNavigation: "NAVEGACIÓN ACTIVA",
    currentPosition: "Posición Actual",
    passengers: "Pasajeros",
    capacity: "Capacidad",
    seats: "Asientos",
    timeLeft: "min restantes",
    estArrival: "Llegada Est.",
    onBoardPassengers: "Pasajeros a Bordo",
    studentId: "ID Estudiante",
    paid: "PAGADO",
    managePassengers: "Gestionar Pasajeros",
    routeAlerts: "Alertas de Ruta",
    routeAlertsDesc: "Tráfico pesado detectado cerca de Villa Altagracia. Retraso est.: 15 mins.",
    validation: "Validación",
    validationDesc: "Licencia de conducir verificada. El seguro expira en 45 días.",
    greenPoints: "Puntos Verdes",
    greenPointsDesc: "¡Has ganado 450 puntos este mes por compartir tu viaje!",
    // Perfil (Profile)
    editProfile: "Editar Perfil",
    driverScore: "Puntuación Chofer",
    tripsCompleted: "VIAJES COMPLETADOS",
    safeDriverStreak: "RACHA DE CONDUCTOR SEGURO",
    totalEarnings: "GANANCIAS TOTALES",
    vehicleDetails: "Detalles del Vehículo",
    plate: "Placa",
    verified: "VERIFICADO",
    addNewVehicle: "Añadir Nuevo Vehículo",
    recentActivity: "Actividad Reciente",
    // Ajustes (Settings)
    accountPreferences: "Preferencias de Cuenta",
    displayName: "NOMBRE VISIBLE",
    institutionalEmail: "CORREO INSTITUCIONAL",
    emailCannotChange: "Los correos institucionales no se pueden cambiar.",
    notifications: "Notificaciones",
    tripConfirmations: "Confirmaciones de Viaje",
    tripConfirmationsDesc: "Recibe alertas cuando un pasajero reserva tu viaje.",
    chatMessages: "Mensajes de Chat",
    chatMessagesDesc: "Recibe notificaciones cuando alguien te envía un mensaje directo.",
    appUpdates: "Actualizaciones de la App",
    appUpdatesDesc: "Mantente informado sobre nuevas funciones y noticias del campus.",
    privacySafety: "Privacidad y Seguridad",
    womenOnlyRides: "Viajes Solo Mujeres",
    womenOnlyRidesDesc: "Solo mostrar mi perfil a otras estudiantes verificadas.",
    showPhoneNumber: "Mostrar Número de Teléfono",
    showPhoneNumberDesc: "Permitir que los pasajeros confirmados vean tu número de teléfono.",
    discardChanges: "Descartar Cambios",
    saveChanges: "Guardar Cambios",
    // Mis Viajes (My Rides)
    activeRides: "Viajes Activos",
    pastRides: "Viajes Pasados",
    passenger: "PASAJERO",
    driver: "CHOFER",
    price: "Precio",
    earnings: "Ganancias",
    details: "Detalles",
    message: "Mensaje",
    manage: "Gestionar",
    // Detalles del Viaje (Ride Details)
    backToResults: "Volver a Resultados",
    institutionalDriver: "CHOFER INSTITUCIONAL",
    smokingFree: "LIBRE DE HUMO",
    travelPreferences: "Preferencias de Viaje",
    noSmallTalk: "Poca conversación",
    spotifyAvailable: "Spotify disponible",
    noPets: "Sin mascotas",
    musicLover: "Amante de la música",
    acOnHigh: "Aire acondicionado alto",
    friendlyChat: "Conversación amigable",
    singlePassengerSeat: "Asiento de pasajero individual",
    rideFare: "Tarifa del viaje",
    serviceFee: "Tarifa de servicio",
    total: "Total",
    bookThisRide: "Reservar este Viaje",
    cancellationFree: "La cancelación es gratuita hasta 2 horas antes de la salida.",
    inHours: "En ~2.5 horas",
    liveRouteInsights: "Información de Ruta en Vivo (IA)",
    analyzingRoute: "Analizando ruta con datos de Google Maps...",
    viewOnMaps: "Ver en Maps",
    unableToLoadRoute: "No se pudo cargar la información de la ruta en vivo."
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<Language>('es');

  const t = (key: string) => {
    return translations[lang][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
